---

- name: Add a docker configuration file
  become: yes
  template:
    dest: /etc/docker/daemon.json
    group: root
    mode: 0444
    owner: root
    src: daemon.json.j2
  register: docker_config_file

- name: Ensure Docker service is restarted with configuration changes
  become: yes
  service:
    name: docker
    state: restarted
  when: docker_config_file.changed

- name: Ensure Docker service starts at boot
  become: yes
  service:
    name: docker
    state: started
