---

- name: Add a docker configuration file
  become: yes
  template:
    dest: /etc/docker/daemon.json
    group: root
    mode: 0444
    owner: root
    src: daemon.json.j2
  register: docker_config_file

- name: Wait for thin pool device to be available
  become: yes
  wait_for:
    path: "{{ sansible_docker_thin_pool_device }}"
    state: present
  when: sansible_docker_thin_pool_device is not none

- name: Ensure Docker service is restarted with configuration changes
  become: yes
  service:
    name: docker
    state: restarted
  when: docker_config_file.changed
  tags:
    - skip_ansible_lint

- name: Ensure Docker service starts at boot
  become: yes
  service:
    name: docker
    state: started
    enabled: yes
  when: ansible_virtualization_type != 'docker'
