---

- name: Install Essential Packages
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl

- name: Install thin-provisioning-tools if Required
  become: yes
  apt:
    name: "thin-provisioning-tools={{ sansible_docker_thin_provisioning_tools_version }}"
  when: sansible_docker_thin_pool_device is not none

- name: Install kernel extras
  become: yes
  apt:
    name: "linux-image-extra-{{ ansible_kernel }}"
  when: ansible_distribution_release == 'trusty'
          and
        ansible_virtualization_type != 'docker'

- name: Add Docker GPG Key
  become: yes
  apt_key:
    keyserver: "{{ sansible_docker_repo_keyserver }}"
    id: "{{ sansible_docker_repo_key_id}}"
    state: present

- name: Add Docker Repo
  become: yes
  apt_repository:
    repo: "{{ sansible_docker_repo }}"
    state: present
    update_cache: yes

- name: Install Docker
  become: yes
  apt:
    name: "{{ 'docker-ce=' + sansible_docker_version if sansible_docker_version else 'docker-ce' }}"

- name: Create /etc/docker
  become: yes
  file:
    group: root
    mode: 0755
    owner: root
    path: /etc/docker
    state: directory

- name: Add Workspace User to Docker Group
  become: yes
  user:
    append: yes
    groups: docker
    name: "{{ sansible_docker_workspace_user }}"
  when: sansible_docker_workspace_user is not none
