---

- name: Install Essential Packages
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl

- name: Install thin-provisioning-tools if Required
  become: yes
  apt:
    name: "thin-provisioning-tools={{ sansible_docker_thin_provisioning_tools_version }}"
  when:
    - sansible_docker_daemon_config is not none
    - "'storage-driver' in sansible_docker_daemon_config"
    - sansible_docker_daemon_config['storage-driver'] == "devicemapper"

- name: Install kernel extras
  become: yes
  apt:
    name: "linux-image-extra-{{ ansible_kernel }}"
  when:
    - ansible_distribution_release == 'trusty'
    - ansible_virtualization_type != 'docker'

- name: Download Docker PGP key (works with Bionic behind a proxy)
  become: yes
  get_url:
    dest: /usr/local/src/docker.asc
    mode: 0644
    url: "{{ sansible_docker_repo_keyserver }}/pks/lookup?op=get&search=0x{{ sansible_docker_repo_key_id }}"
  retries: 2
  delay: 10
  register: sansible_docker_pgp_result
  until: sansible_docker_pgp_result is succeeded

- name: Ensures Docker PGP key is known
  become: yes
  apt_key:
    file: /usr/local/src/docker.asc
    id: "{{ sansible_docker_repo_key_id }}"
    state: present

- name: Add Docker Repo
  become: yes
  apt_repository:
    repo: "{{ sansible_docker_repo }}"
    state: present
    update_cache: yes

- name: Install Docker
  become: yes
  apt:
    name: "{{ 'docker-ce=' + sansible_docker_version if sansible_docker_version else 'docker-ce' }}"

- name: Create /etc/docker
  become: yes
  file:
    group: root
    mode: 0755
    owner: root
    path: /etc/docker
    state: directory

- name: Add Workspace User to Docker Group
  become: yes
  user:
    append: yes
    groups: docker
    name: "{{ sansible_docker_workspace_user }}"
  when: sansible_docker_workspace_user is not none
