---

- name: Install essential packages
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl

- name: Install thin-provisioning-tools if required
  become: yes
  apt:
    name: "thin-provisioning-tools={{ docker.package_version.thin_provisioning_tools }}"
  when: docker.thin_pool_device is not none

- name: Install kernel extras
  become: yes
  apt:
    name: "linux-image-extra-{{ ansible_kernel }}"
  when: ansible_distribution_release == "trusty"

- name: Add Docker gpg key
  become: yes
  apt_key:
    keyserver: "{{ docker.repo_keyserver }}"
    id: "{{ docker.repo_key_id }}"
    state: present

- name: Install Docker repo
  become: yes
  apt_repository:
    repo: "{{ docker.repo }}"
    state: present
    update_cache: yes

- name: Install Docker
  become: yes
  apt:
    name: "{{ 'docker-ce=' + docker.version if docker.version else 'docker-ce' }}"

- name: Create /etc/docker
  become: yes
  file:
    group: root
    mode: 0755
    owner: root
    path: /etc/docker
    state: directory

- name: Add workspace user to docker group
  become: yes
  user:
    append: yes
    groups: docker
    name: "{{ docker.workspace_user }}"
  when: docker.workspace_user
