---

- name: Assert thinpool not used on trusty
  assert:
    that:
      - sansible_docker_daemon_config['storage-driver'] != "devicemapper"
  when:
    - sansible_docker_daemon_config is not none
    - "'storage-driver' in sansible_docker_daemon_config"
    - ansible_distribution_release == 'trusty'
  tags:
    - always

- name: Assert thinpool config makes sense
  assert:
    that:
      - "'storage-opts' in sansible_docker_daemon_config"
      - sansible_docker_daemon_config['storage-opts'] | select('match', '^dm.directlvm_device=.*') | list | length == 1
  when:
    - sansible_docker_daemon_config is not none
    - "'storage-driver' in sansible_docker_daemon_config"
    - sansible_docker_daemon_config['storage-driver'] == "devicemapper"
  tags:
    - always

- name: Install Docker
  include: install.yml
  tags:
    - build

- name: Configure Docker
  include: configure.yml
  tags:
    - configure
