---

- name: Assert supported options
  assert:
    that:
     - docker.thin_pool_device is none
  when: ansible_distribution_release == "trusty"
  tags:
    - always

- name: Install Docker
  include: install.yml
  tags:
    - build

- name: Configure Docker
  include: configure.yml
  tags:
    - configure
