---

- name: reload docker
  become: yes
  service:
    name: docker
    state: reloaded

- name: restart docker
  become: yes
  service:
    name: docker
    state: restarted

- name: start docker
  become: yes
  service:
    name: docker
    state: started

- name: stop docker
  become: yes
  service:
    name: docker
    state: stopped
